name: Build and push Docker container
on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 2 * * 1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine metadata
        run: |
          SHORT_COMMIT=$(echo $GITHUB_SHA | cut -c1-8)
          BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          echo "short_commit=${SHORT_COMMIT}" >> $GITHUB_ENV
          echo "build_date=${BUILD_DATE}" >> $GITHUB_ENV

          echo "Short Commit: ${SHORT_COMMIT}"
          echo "Build Date: ${BUILD_DATE}"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container
        run: >
          docker buildx build --push
          --build-arg BUILD_DATE=${{ env.build_date }}
          --build-arg SOURCE_COMMIT=$GITHUB_SHA
          -t "ghcr.io/parad0x3dart/linktree:latest"
          .