name: Build and push Docker container
on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 2 * * 1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine metadata
        run: |
          SHORT_COMMIT=$(echo $GITHUB_SHA | cut -c1-8)
          BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          echo "build_date=${BUILD_DATE}" | tee -a $GITHUB_ENV
          echo "short_commit=${SHORT_COMMIT}" | tee -a $GITHUB_ENV

      - name: Build container
        run: >
          docker buildx build --push
          --platform linux/amd64
          --build-arg BUILD_DATE=${{ env.build_date }}
          --build-arg SOURCE_COMMIT=$GITHUB_SHA
          -t "ghcr.io/parad0x3Dart/linktree"
          .